### ISSUE TITLE
Investigate large Image Viewer (light box pop-up etc, )

### ISSUE THREAD

**Issue by alexmerrill** [MukurtuCMS/Mukurtu-CMS#203] opened 2024-01-17 00:52 UTC
If memory serves we use colorbox in Mukurtu 3  -- looks like we might be able to use the same module and, maybe similar approach in 4 as there is a Drupal 9/10 version, but we should/could verify approach...

https://www.drupal.org/project/colorbox

**Comment by michael-wynne-wsu** [comment] 2024-05-08 16:10
@pjudge a few questions/notes on this.

1) The "close" button on the open lightbox feels oddly placed to me. Is that as intended and I'm the only one thinking it feels off?

2) It looks like the lightbox takes the image to 100% OR scale down to fit the window size if it's larger. In the case of the newspaper below that actually ends up being smaller than the in-page view. 
2a) Are there options to include zoom controls? Without that it doesn't really add anything (I'm thinking that my request didn't give the right details though!)Here's the same image in a production site now - that lightbox ONLY zooms to 100% with no controls so it's too far the other way. 

This might be something we want to discuss/email in more detail before closing or working on more - let me know.

![Screenshot 2024-05-08 at 9 03 09 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/08b67972-af8e-4451-9119-e0ca36483df4)

![YNR_V24N02_01](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/76f94881-441e-4dec-8e86-20ce0c122dc8)

![Screenshot 2024-05-08 at 9 03 47 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/cbe3b53b-e2a2-496d-a4fc-562565f46140)


![Screenshot 2024-05-08 at 9 02 59 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/af771e52-59ee-4071-bda3-6faab1aece45)

**Comment by michael-wynne-wsu** [comment] 2024-05-09 15:44
This is good now, thanks!

**Closed by michael-wynne-wsu** 2024-05-09 15:44 UTC
Labels: enhancement, theme/look and feel, media
