### ISSUE TITLE
LC Label Hub project pages

### ISSUE THREAD

**Issue by taylor-steve** [MukurtuCMS/Mukurtu-CMS#137] opened 2023-11-15 18:49 UTC
Create three new pages (routes TBD/best guess):

* Site level page, linking to all active site wide Hub projects
* Community level page, linking to all active Hub projects for that community
* Protocol level page, linking to all active Hub projects for that protocol

Note: For the links, the level of access of the user is not a consideration. "Active" in this context only means the page is available to the public on the Hub. We'll need to make API calls/GET the page as appropriate. Likely we'll need to cache that result, because the Hub is quite slow to respond in the context of real time calls.

**Comment by steve-taylor-wsu** [comment] 2023-11-15 19:00
Oh sandbox.localcontextshub.org is faster, maybe we can get away with on demand calls?

**Comment by michael-wynne-wsu** [comment] 2023-11-15 22:28
1) I don't think hub project descriptions are essential, so that's okay. A text field for the page as a whole will be useful in place.

2) I would like to have the label text as well.

3) I suspect this will turn to chaos if they have many projects with overlapping labels, but that might just be the way it is, unless we gave control to omit/select projects.

**Comment by steve-taylor-wsu** [comment] 2023-11-15 23:06
1. Okay I added a text box you can configure. Note that this isn't a fieldable entity (e.g., it's not a "Basic Page"), it's a templated page, so there are no fields. I've added a config form for the page that has a single text box for a description. At some point we'll need default text for this to ship with, provided we keep this format.
2. Everything we have is available in the template. I've now added the label text to the display in the default template.
3. This is why I was thinking icons/tooltips only. Keep things compact, push folks to the hub for the actual details. I don't think it's a big deal though. For sites where this truly is chaos, they can override the template to show less information.

**Comment by steve-taylor-wsu** [comment] 2023-11-15 23:16
For groups (communities/protocols) is the desire to have the text from 1 configurable per group? I'm assuming so.

**Comment by michael-wynne-wsu** [comment] 2023-11-16 03:35
> For groups (communities/protocols) is the desire to have the text from 1 configurable per group? I'm assuming so.

Yes, exactly, thanks!

**Comment by michael-wynne-wsu** [comment] 2023-11-27 20:34
Looks like Passamaquoddy is back up: https://passamaquoddypeople.com/passamaquoddy-traditional-knowledge-labels 

I don't think that affects anything done to date, but it's there as a reference.

**Comment by michael-wynne-wsu** [comment] 2023-12-04 17:59
Notes:

1) /local-contexts/projects was inaccessible until a project had been added. Not an issue per se, but we might not want to give that link until it's active, or provide placeholder text.

2) Above page threw an error after I added a project but before I added a description at /local-contexts/projects/directory (forgot to grab the error - I removed the description and it's fine now)

3) Community directory is throwing an error (I do .
![Screenshot 2023-12-04 at 9 57 13 AM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/af96e84e-a409-4558-bc91-4688d5991695)

**Comment by nick-deer** [comment] 2023-12-04 21:24
@michael-wynne-wsu Thanks for your feedback, and for catching those errors! I pushed up some changes:

1.  /local-contexts/projects is now accessible even if there are no projects. A message displays if there are no projects.
2. Fixed this error
3. Fixed this error

**Comment by michael-wynne-wsu** [comment] 2023-12-04 21:39
Confirmed that it's all working now!

Do you want thoughts on layout or are we in strict functionality for this? Or more generally - this is a great working pass, how can I guide you from here?

**Comment by nick-deer** [comment] 2023-12-05 00:38
Good question! I think this first pass was strictly for functionality, so if you find it acceptable, we can start another pass for layout feedback/other feedback if you've got it. It's kind of tricky since we don't have user stories or user acceptance criteria for this, so I'm relying on your user expertise :)

**Comment by michael-wynne-wsu** [comment] 2023-12-05 17:31
Okay here is an effort at high level acceptance criteria! Obviously we should discuss more - let me know how you want to do that. And if any of this is contradictory to previous work or just off, let me know. Some of these are included in the functionality pass, just listing everything I can think of.

1) The directory page should display all LC Hub projects at the relevant level (site, community).
2) The directory page should display all labels and notices from each project. They should be grouped by type (eg: TK Labels together, BC Labels together).
3) The directory page should have some visual distinction between projects. Consider tabs, accordions, or anchors? (I do have some ideas about visuals but not sure if you want that)
4) The directory page should display the name of the projects.
5) The directory page should include space for an overview/introduction/narrative. Unsure yet if this should be per-project or per-directory.

**Comment by nick-deer** [comment] 2023-12-08 21:04
@michael-wynne-wsu Thank you this is very helpful! About 3, your ideas on visuals are welcome!

**Comment by michael-wynne-wsu** [comment] 2024-02-13 23:27
/dashboard/local-contexts/projects/directory

Directory description should be HTML not plain text.

**Comment by michael-wynne-wsu** [comment] 2024-02-28 21:07
Would like to add options to select display of icons, icons + title, or icons + title + text, like the Hubs new embed code allows.

**Comment by michael-wynne-wsu** [comment] 2024-09-27 21:33
Update/clarify, this IS only theming

**Comment by michael-wynne-wsu** [comment] 2024-10-03 18:00
@nick-deer FYI I'm closing this because I made a new issue for the theming components, and a new issue for one tiny back end change. This aspect of the feature is done.

**Closed by michael-wynne-wsu** 2024-10-03 18:00 UTC
Labels: theme/look and feel, Local Contexts, all pages (theme) review
