### ISSUE TITLE
Collections inaccessible to most users

### ISSUE THREAD

**Issue by taylor-steve** [MukurtuCMS/Mukurtu-CMS#162] opened 2023-11-22 00:52 UTC
Seems like a collections permission may have gotten dropped somewhere. Reported that only UID 1 can access collection entities.

* Find and Fix
* Double check that the collection tests are using the same permission sets

**Comment by nick-deer** [comment] 2024-02-07 23:37
@michael-wynne-wsu I finally fixed it! It wasn't a permissions issue, rather, nothing in the system was ever granting access allowed to viewing collections entities (it was only granting access neutral and apparently that wasn't good enough). I added that and it looks like everything is running smoothly. Let me know if that's true for you as well!

**Comment by michael-wynne-wsu** [comment] 2024-02-08 00:01
@nick-deer confirmed on a fresh gitpod install that it's working, thank you!

I have only tested with admin/anonymous, not members with alternate membership, but that will go into my overall protocol behaviour checks. You're good to close this whenever.

**Closed** 2024-02-08 20:50 UTC
